/*
File written by Jeremy Hamilton
*/

//larger constructions
#define GLUE "GLUE"
#define FUNCTION_DEF "FUNCTION_DEF"
#define PARAMETERS "PARAMETERS"
#define BODY "BODY"
#define GLOBAL "GLOBAL"
#define FUNCTION_CALL "FUNCTION_CALL"
#define EXPRESSION "EXPRESSION"
#define LIST "LIST"
#define ARRAY "ARRAY"
#define CLOSURE "CLOSURE"
#define ENV "ENV"

//individual parts
#define CBRACKET "CBRACKET"
#define OBRACKET "OBRACKET"
#define PERIOD   "PERIOD"
#define SEMICOLON "SEMICOLON"
#define COLON    "COLON"
#define COMMA    "COMMA"
#define VARIABLE "VARIABLE"
#define WHILE    "WHILE"
#define IF       "IF"
#define ELSE     "ELSE"
#define RETURN   "RETURN"
#define STRING   "STRING"
#define ASSIGN   "ASSIGN"
#define NUMBER   "NUMBER"
#define PLUS	 "PLUS"
#define TIMES    "TIMES"
#define DIVIDE   "DIVIDE"
#define SUBTRACT "SUBTRACT"
#define MODULUS  "MODULUS"
#define AND      "AND"
#define OR       "OR"
#define NOT      "NOT"
#define XOR      "XOR"
#define EQUALS   "EQUALS"
#define NOTEQUALS "NOTEQUALS"
#define LESSTHAN "LESSTHAN"
#define GREATERTHAN "GREATERTHAN"
#define LESSOREQUAL "LESSOREQUAL"
#define GREATEROREQUAL "GREATEROREQUAL"
#define FUNCTION   "FUNCTION"
#define ENDOFINPUT "ENDOFINPUT"
#define UNKNOWN  "UNKOWN"
